apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: bhargavshah86/kube-test:v0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
      nodePort: {{ .Values.nodePort }}
      drink: {{ .Values.favorite.drink }}
      food: {{ .Values.favorite.food }}      
  type: NodePort